services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money_blockchain
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass Dkrlrhfo0992!
    ports:
      - "6379:6379"
    networks:
      - backend

  spring-money:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-money-container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
