services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money_blockchain
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass 9999
    ports:
      - "6379:6379"
    networks:
      - backend
# 빌드 버전
#  spring-money:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-money-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    networks:
#      - backend

# 도커 허브에 올릴때 image
  spring-money:
    image: agigora/money-spring-money:latest
    container_name: spring-money-container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
