package Baeksa.money.domain.fcm;

public enum NotiType {
    REGISTER_USER, APPROVE_MEMBERSHIP, REJECT_MEMBERSHIP,
    STUDENT_APPLY_LEDGER, STUDENT_VOTE_WITHDRAW,
    COMMITTEE_APPLY_WITHDRAW, COMMITTEE_APPROVE_DEPOSIT, COMMITTEE_REJECT_DEPOSIT
}
